import tkinter as tk
from PIL import Image, ImageTk, Image
import customtkinter as ctk

kanji_list =["日", "一", "国",  "人", "年", "大", "十", "二", "本", "中", "長", "出", "三", "時", "行",
              "見", "月", "分", "後", "前", "生", "五", "間", "上", "東", "四", "今", "金", "九", "入",
              "学", "高", "円", "子", "外", "八", "六", "下", "来", "気", "小", "七", "山", "話", "女",
              "北", "午", "百", "書", "先", "名", "川", "千", "水", "半", "男", "西", "電", "校", "語",
              "土", "木", "聞", "食", "車", "何", "南", "万", "毎", "白", "天", "母", "火", "右", "読",
              "友", "左", "休", "父", "雨"]

diction = [
  { 'name' : "日",
    "meaning": {"sun": ImageTk.PhotoImage(Image.open("./new_pics/sun.png").resize((400, 425))),
                "day": ImageTk.PhotoImage(Image.open("./new_pics/day.png").resize((400, 425)))}},
  { 'name' : "一",
    "meaning": {"one": ImageTk.PhotoImage(Image.open("./new_pics/one.png").resize((400, 425)))}},
  { 'name' : "国",
    "meaning": {"country": ImageTk.PhotoImage(Image.open("./new_pics/country.png").resize((400, 425)))}},
  { 'name' : "人",
    "meaning": {"person" : ImageTk.PhotoImage(Image.open("./new_pics/person.png").resize((400, 425)))}},
  { 'name' : "年",
    "meaning": {"year" : ImageTk.PhotoImage(Image.open("./new_pics/year.png").resize((400, 425)))}},
  { 'name' : "大",
    "meaning" : {"big" : ImageTk.PhotoImage(Image.open("./new_pics/big.png").resize((400, 425)))}},
  { 'name' : "十",
    "meaning" : {"ten" : ImageTk.PhotoImage(Image.open("./new_pics/ten.png").resize((400, 425)))}},
  { 'name' : "二",
    "meaning" : {"two" : ImageTk.PhotoImage(Image.open("./new_pics/two.png").resize((400, 425)))}},
  { 'name' : "本",
    "meaning" : {"book" : ImageTk.PhotoImage(Image.open("./new_pics/book.png").resize((400, 425)))}},
  { 'name' : "中",
    "meaning" : {"middle" : ImageTk.PhotoImage(Image.open("./new_pics/middle.png").resize((400, 425)))}},
  { 'name' : "長",
    "meaning" : {"long" : ImageTk.PhotoImage(Image.open("./new_pics/long.png").resize((400, 425)))}},
  { 'name' : "出",
    "meaning" : {"go out" : ImageTk.PhotoImage(Image.open("./new_pics/go_out.png").resize((400, 425)))}},
  { 'name' : "三",
    "meaning" : {"three": ImageTk.PhotoImage(Image.open("./new_pics/three.png").resize((400, 425)))}},
  { 'name' : "時",
    "meaning" : {"time" : ImageTk.PhotoImage(Image.open("./new_pics/time.png").resize((400, 425)))}}, #change
  { 'name' : "行",
    "meaning" : {"to go" : ImageTk.PhotoImage(Image.open("./new_pics/to_go.png").resize((400, 425)))}},
  { 'name' : "見",
    "meaning" : {"see" : ImageTk.PhotoImage(Image.open("./new_pics/see.png").resize((400, 425)))}},
  { 'name' : "月",
    "meaning" : {"month" : ImageTk.PhotoImage(Image.open("./new_pics/month.png").resize((400, 425))),
                "moon" : ImageTk.PhotoImage(Image.open("./new_pics/moon.png").resize((400, 425)))}},
  { 'name' : "分",
    "meaning" : {"divide" : ImageTk.PhotoImage(Image.open("./new_pics/divide.png").resize((400, 425)))}},
  { 'name' : "後",
    "meaning" : {"after" : ImageTk.PhotoImage(Image.open("./new_pics/after.png").resize((400, 425)))}},
  { 'name' : "前",
    "meaning" : {"before" : ImageTk.PhotoImage(Image.open("./new_pics/before.png").resize((400, 425)))}},
  { 'name' : "生",
    "meaning" : {"life" : ImageTk.PhotoImage(Image.open("./new_pics/life.png").resize((400, 425)))},
                  "to be born" : ImageTk.PhotoImage(Image.open("./new_pics/be_born.png").resize((400, 425)))},
  { 'name' : "五",
    "meaning" : {"five" : ImageTk.PhotoImage(Image.open("./new_pics/five.png").resize((400, 425)))}},
  { 'name' : "間",
    "meaning" : {"interval" : ImageTk.PhotoImage(Image.open("./new_pics/interval.png").resize((400, 425)))}},
  { 'name' : "上",
    "meaning" : {"above" : ImageTk.PhotoImage(Image.open("./new_pics/above.png").resize((400, 425)))}},
  { 'name' : "東",
    "meaning" : {"east" : ImageTk.PhotoImage(Image.open("./new_pics/east.png").resize((400, 425)))}},
  { 'name' : "四",
    "meaning" : {"four" : ImageTk.PhotoImage(Image.open("./new_pics/four.png").resize((400, 425)))}},
  { 'name' : "今",
    "meaning" : {"now" : ImageTk.PhotoImage(Image.open("./new_pics/now.png").resize((400, 425)))}},
  { 'name' : "金",
    "meaning" : {"gold" : ImageTk.PhotoImage(Image.open("./new_pics/gold.png").resize((400, 425)))}},
  { 'name' : "九",
    "meaning" : {"nine" : ImageTk.PhotoImage(Image.open("./new_pics/nine.png").resize((400, 425)))}},
  { 'name' : "入",
    "meaning" : {"enter" : ImageTk.PhotoImage(Image.open("./new_pics/enter.png").resize((400, 425)))}},
  { 'name' : "学",
    "meaning" : {"learn" : ImageTk.PhotoImage(Image.open("./new_pics/learn.png").resize((400, 425)))}},
  { 'name' : "高",
    "meaning" : {"expensive" : ImageTk.PhotoImage(Image.open("./new_pics/expensive.png").resize((400, 425))),
                "high" : ImageTk.PhotoImage(Image.open("./new_pics/high.png").resize((400, 425)))}},
  { 'name' : "円",
    "meaning" : {"circle" : ImageTk.PhotoImage(Image.open("./new_pics/circle.png").resize((400, 425))),
                "yen" : ImageTk.PhotoImage(Image.open("./new_pics/yen.png").resize((400, 425)))}},
  { 'name' : "子",
    "meaning" : {"child" : ImageTk.PhotoImage(Image.open("./new_pics/child.png").resize((400, 425)))}},
  { 'name' : "外",
    "meaning" : {"outside" : ImageTk.PhotoImage(Image.open("./new_pics/outside.png").resize((400, 425)))}},
  { 'name' : "八",
    "meaning" : {"eight" : ImageTk.PhotoImage(Image.open("./new_pics/eight.png").resize((400, 425)))}},
  { 'name' : "六",
    "meaning" : {"six" : ImageTk.PhotoImage(Image.open("./new_pics/six.png").resize((400, 425)))}},
  { 'name' : "下",
    "meaning" : {"below" : ImageTk.PhotoImage(Image.open("./new_pics/under.png").resize((400, 425)))}},
  { 'name' : "来",
    "meaning" : {"come" : ImageTk.PhotoImage(Image.open("./new_pics/come.gif").resize((400, 425)))}},
  { 'name' : "気",
    "meaning" : {"spirit" : ImageTk.PhotoImage(Image.open("./new_pics/spirit.png").resize((400, 425)))}},
  { 'name' : "小",
    "meaning" : {"small" : ImageTk.PhotoImage(Image.open("./new_pics/small.png").resize((400, 425)))}},
  { 'name' : "七",
    "meaning" : {"seven" : ImageTk.PhotoImage(Image.open("./new_pics/seven.png").resize((400, 425)))}},
  { 'name' : "山",
    "meaning" : {"mountain" : ImageTk.PhotoImage(Image.open("./new_pics/mountain.png").resize((400, 425)))}},
  { 'name' : "女",
    "meaning" : {"woman" : ImageTk.PhotoImage(Image.open("./new_pics/woman.png").resize((400, 425))),
                "female" : ImageTk.PhotoImage(Image.open("./new_pics/woman.png").resize((400, 425)))}},
  { 'name' : "北",
    "meaning" : {"north" : ImageTk.PhotoImage(Image.open("./new_pics/north.png").resize((400, 425)))}},
  { 'name' : "午",
    "meaning" : {"noon" : ImageTk.PhotoImage(Image.open("./new_pics/noon.png").resize((400, 425)))}},
  { 'name' : "百",
    "meaning" : {"hundred" : ImageTk.PhotoImage(Image.open("./new_pics/hundred.png").resize((400, 425)))}},
  { 'name' : "書",
    "meaning" : {"write" : ImageTk.PhotoImage(Image.open("./new_pics/write.png").resize((400, 425)))}},
  { 'name' : "先",
    "meaning" : {"ahead" : ImageTk.PhotoImage(Image.open("./new_pics/ahead.png").resize((400, 425)))}},
  { 'name' : "名",
    "meaning" : {"name" : ImageTk.PhotoImage(Image.open("./new_pics/name.png").resize((400, 425)))}},
  { 'name' : "川",
    "meaning" : {"river" : ImageTk.PhotoImage(Image.open("./new_pics/river.png").resize((400, 425)))}},
  { 'name' : "千",
    "meaning" : {"thousand" : ImageTk.PhotoImage(Image.open("./new_pics/thousand.png").resize((400, 425)))}},
  { 'name' : "水",
    "meaning" : {"water" : ImageTk.PhotoImage(Image.open("./new_pics/water.png").resize((400, 425)))}},
  { 'name' : "半",
    "meaning" : {"half" : ImageTk.PhotoImage(Image.open("./new_pics/half.png").resize((400, 425)))}},
  { 'name' : "男",
    "meaning" : {"male" : ImageTk.PhotoImage(Image.open("./new_pics/man.png").resize((400, 425)))}},
  { 'name' : "西",
    "meaning" : {"west" : ImageTk.PhotoImage(Image.open("./new_pics/west.png").resize((400, 425)))}},
  { 'name' : "電",
    "meaning" : {"electricity" : ImageTk.PhotoImage(Image.open("./new_pics/electricity.png").resize((400, 425)))}},
  { 'name' : "校",
    "meaning" : {"exam" : ImageTk.PhotoImage(Image.open("./new_pics/exam.png").resize((400, 425)))}},
  { 'name' : "語",
    "meaning" : {"talk" : ImageTk.PhotoImage(Image.open("./new_pics/talk.png").resize((400, 425)))}},
  { 'name' : "土",
    "meaning" : {"ground" : ImageTk.PhotoImage(Image.open("./new_pics/ground.png")),
                "earth" : ImageTk.PhotoImage(Image.open("./new_pics/ground.png").resize((400, 425)))}},
  { 'name' : "木",
    "meaning" : {"tree" : ImageTk.PhotoImage(Image.open("./new_pics/tree.png").resize((400, 425)))}},
  { 'name' : "聞",
    "meaning" : {"listen" : ImageTk.PhotoImage(Image.open("./new_pics/listen.png").resize((400, 425)))}},
  { 'name' : "食",
    "meaning" : {"eat" : ImageTk.PhotoImage(Image.open("./new_pics/eat.gif").resize((400, 425))),
                "food" : ImageTk.PhotoImage(Image.open("./new_pics/food.png").resize((400, 425)))}},
  { 'name' : "車",
    "meaning" : {"car" : ImageTk.PhotoImage(Image.open("./new_pics/car.png").resize((400, 425)))}},
  { 'name' : "何",
    "meaning" : {"what" : ImageTk.PhotoImage(Image.open("./new_pics/what.gif").resize((400, 425)))}},
  { 'name' : "南",
    "meaning" : {"south" : ImageTk.PhotoImage(Image.open("./new_pics/south.png").resize((400, 425)))}},
  { 'name' : "万",
    "meaning" : {"ten thousand" : ImageTk.PhotoImage(Image.open("./new_pics/thousand.png").resize((400, 425)))}},
  { 'name' : "毎",
    "meaning" : {"every" : ImageTk.PhotoImage(Image.open("./new_pics/every.png").resize((400, 425))),
                "each" : ImageTk.PhotoImage(Image.open("./new_pics/every.png").resize((400, 425)))}},
  { 'name' : "白",
    "meaning" : {"white" : ImageTk.PhotoImage(Image.open("./new_pics/white.png").resize((400, 425)))}},
  { 'name' : "天",
    "meaning" : {"heaven" : ImageTk.PhotoImage(Image.open("./new_pics/heaven.png").resize((400, 425)))}},
  { 'name' : "母",
    "meaning" : {"mother" : ImageTk.PhotoImage(Image.open("./new_pics/mother.png").resize((400, 425)))}},
  { 'name' : "火",
    "meaning" : {"fire" : ImageTk.PhotoImage(Image.open("./new_pics/fire.png").resize((400, 425)))}},
  { 'name' : "右",
    "meaning" : {"right" : ImageTk.PhotoImage(Image.open("./new_pics/right.png").resize((400, 425)))}},
  { 'name' : "読",
    "meaning" : {"read" : ImageTk.PhotoImage(Image.open("./new_pics/read.png").resize((400, 425)))}},
  { 'name' : "友",
    "meaning" : {"friend" : ImageTk.PhotoImage(Image.open("./new_pics/friend.png").resize((400, 425)))}},
  { 'name' : "左",
    "meaning" : {"left" : ImageTk.PhotoImage(Image.open("./new_pics/left.png").resize((400, 425)))}},
  { 'name' : "休",
    "meaning" : {"rest" : ImageTk.PhotoImage(Image.open("./new_pics/rest.png").resize((400, 425)))}},
  { 'name' : "父",
    "meaning" : {"father" : ImageTk.PhotoImage(Image.open("./new_pics/father.png").resize((400, 425)))}},
  { 'name' : "雨",
    "meaning" : {"rain" : ImageTk.PhotoImage(Image.open("./new_pics/rain.png").resize((400, 425)))}}
]





